import InputLabel from "@design-system/components/inputs/label";
import {
  Radio,
  RadioIndicator,
  RadioItem,
} from "@design-system/components/inputs/radio";
import Flex from "@design-system/components/layout/flex";
import KYCSteps from "@design-system/templates/complete-kyc/KYC-steps";
import UserKYCDesc from "@design-system/templates/complete-kyc/User-kyc-desc";
import DashboardPanel from "@design-system/components/layout/dashhboard-panel";
import Layout from "@design-system/templates/shared/layout";
import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";

const starters = [
  { id: "red", title: "Verify Email" },
  { id: "green", title: "Add Personal Detials" },
  { id: "blue", title: "Business Details" },
  { id: "pink", title: "Upload KYC Document" },
];

const CompleteKYC: NextPage = () => {
  const [value, setValue] = useState(starters[0].title);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <DashboardPanel classstyle='!bg-white !my-[32px] !px-[40px] !shadow-[0px_6px_12px_rgba(24,_39,_75,_0.12)]'>
          <Flex classstyle='!w-full !space-x-[20px] !items-start !justify-start'>
            {/* Left Pane */}
            <div className='grow flex flex-col space-y-[20px]'>
              <UserKYCDesc />
              <KYCSteps />
            </div>
            {/* Left Pane End */}

            {/* Right Pane */}
            <div className='grow-0 w-[365px] py-[45px] px-[26px] flex flex-col space-y-[20px]'>
              <Radio
                aria-label='Pokemon starters'
                defaultValue={"Verify Email"}
                onValueChange={setValue}
              >
                <div className='space-y-[24px]'>
                  {/* Verify Email */}
                  <div className='flex items-center !space-x-[18px]'>
                    <RadioItem id='Verify Email' value='Verify Email'>
                      <RadioIndicator>
                        <div className='w-2 h-2 rounded-full bg-semBlue600'></div>
                      </RadioIndicator>
                    </RadioItem>
                    <InputLabel
                      labelfor='Verify Email'
                      classstyle='!ml-2 !block !text-sm !font-serif !text-primaryText'
                    >
                      Verify Email
                    </InputLabel>{" "}
                  </div>
                  {/* Verify Email End */}

                  {/* Add Personal Detials */}
                  <div className='flex items-center !space-x-[18px]'>
                    <RadioItem
                      disabled
                      id='Add Personal Detials'
                      value='Add Personal Detials'
                    >
                      <RadioIndicator>
                        <div className='w-2 h-2 rounded-full bg-semBlue600'></div>
                      </RadioIndicator>
                    </RadioItem>
                    <InputLabel
                      labelfor='Add Personal Detials'
                      classstyle='!ml-2 !block !text-sm !font-serif !text-primaryText'
                    >
                      Add Personal Detials
                    </InputLabel>{" "}
                  </div>
                  {/* Add Personal Detials End */}

                  {/* Business Details */}
                  <div className='flex items-center !space-x-[18px]'>
                    <RadioItem
                      disabled
                      id='Business Details'
                      value='Business Details'
                    >
                      <RadioIndicator>
                        <div className='w-2 h-2 rounded-full bg-semBlue600'></div>
                      </RadioIndicator>
                    </RadioItem>
                    <InputLabel
                      labelfor='Business Details'
                      classstyle='!ml-2 !block !text-sm !font-serif !text-primaryText'
                    >
                      Business Details
                    </InputLabel>{" "}
                  </div>
                  {/* Business Details End */}

                  {/* Upload KYC Document */}
                  <div className='flex items-center !space-x-[18px]'>
                    <RadioItem
                      disabled
                      id='Upload KYC Document'
                      value='Upload KYC Document'
                    >
                      <RadioIndicator>
                        <div className='w-2 h-2 rounded-full bg-semBlue600'></div>
                      </RadioIndicator>
                    </RadioItem>
                    <InputLabel
                      labelfor='Upload KYC Document'
                      classstyle='!ml-2 !block !text-sm !font-serif !text-primaryText'
                    >
                      Upload KYC Document
                    </InputLabel>{" "}
                  </div>
                  {/* Upload KYC Document End */}
                </div>
              </Radio>
              {/* <TotalLogs /> */}
            </div>
            {/* Right Pane End */}
          </Flex>
        </DashboardPanel>
      </Layout>
    </div>
  );
};

export default CompleteKYC;
